// Package dto is generated by sqlc https://docs.sqlc.dev/en/stable/index.html
// DO NOT EDIT file suffixed with _gen.go
package dto

// Generate the queries mock
//go:generate mockery --name=Querier --output=mocks --filename=querier.go --outpkg=mocks --srcpkg=.
