// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dto

import (
	"time"
)

type TzktDelegation struct {
	InternalID       int64
	ExternalID       int64
	DelegationDate   time.Time
	DelegatorAddress string
	BlockHash        string
	Amount           string
	BlockState       int64
}
