// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dto

import (
	"context"
)

type Querier interface {
	// DeleteDelegator query function
	// list parameters
	// @from_state::integer define the last valide block state
	DeleteDelegator(ctx context.Context, fromState int32) ([]int64, error)
	// queries for sqlc
	InsertDelegator(ctx context.Context, arg InsertDelegatorParams) (TzktDelegation, error)
	// SearchDelegator query function
	// list parameters
	// @delegation_year::text year of the delegation
	// @limit_item::integer maximum number of items
	SearchDelegator(ctx context.Context, arg SearchDelegatorParams) ([]TzktDelegation, error)
}

var _ Querier = (*Queries)(nil)
